<a href="https://colab.research.google.com/github/antuness/Learning_Python/blob/master/NumPy_B%C3%A1sico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Geral**

In [1]:
import numpy

In [2]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
from numpy import arange

In [6]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np

In [8]:
km = np.array([1000, 2300, 4987, 1500])

In [9]:
km

array([1000, 2300, 4987, 1500])

In [10]:
type(km)

numpy.ndarray

In [11]:
km.dtype

dtype('int64')

In [12]:
km = np.loadtxt(fname = 'carros-km.txt', dtype=int)

In [13]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [14]:
km.dtype

dtype('int64')

In [21]:
dados = [
 ['rodas de liga', 'travas eletricas', 'piloto automatico', 'banco de couro', 'ar condicionado'],
 ['central multimidia', 'teto panoramico', 'freios ABS', 'banco de couro', 'painel digital'],
 ['piloto automatico', 'controle de estabilidade', 'freios ABS', 'banco de couro', 'sensor crepuscular']
]

In [22]:
dados

[['rodas de liga',
  'travas eletricas',
  'piloto automatico',
  'banco de couro',
  'ar condicionado'],
 ['central multimidia',
  'teto panoramico',
  'freios ABS',
  'banco de couro',
  'painel digital'],
 ['piloto automatico',
  'controle de estabilidade',
  'freios ABS',
  'banco de couro',
  'sensor crepuscular']]

In [23]:
acessorios = np.array(dados)

In [24]:
acessorios

array([['rodas de liga', 'travas eletricas', 'piloto automatico',
        'banco de couro', 'ar condicionado'],
       ['central multimidia', 'teto panoramico', 'freios ABS',
        'banco de couro', 'painel digital'],
       ['piloto automatico', 'controle de estabilidade', 'freios ABS',
        'banco de couro', 'sensor crepuscular']], dtype='<U24')

In [25]:
km.shape

(258,)

In [26]:
acessorios.shape

(3, 5)

In [27]:
np_array = np.arange(1000000)

In [28]:
py_list = list(range(1000000))

In [29]:
%time for _ in range(100): np_array *= 2

CPU times: user 54.3 ms, sys: 394 µs, total: 54.7 ms
Wall time: 59.2 ms


In [30]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 9.63 s, sys: 2 s, total: 11.6 s
Wall time: 11.6 s


#**Operações aritméticas**

In [38]:
km = [44410., 5712., 37123., 0., 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [36]:
#idade = 2019 - anos >>> não tem como fazer

In [45]:
km = np.array([44410., 5712., 37123., 0., 25757])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [46]:
idade = 2019 - anos

In [47]:
idade

array([16, 28, 29,  0, 13])

In [48]:
km_media = km / idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


#**Operações com arrays de duas dimensões**

In [49]:
dados = np.array([km, anos])

In [50]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [51]:
dados.shape

(2, 5)

In [52]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [53]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [54]:
km_media = dados [0] / (2019 - dados [1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [55]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [57]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / (altura * altura)
IMC

array([29.36288089, 29.26224956, 24.48979592])

In [60]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / altura ** 2
IMC

array([29.36288089, 29.26224956, 24.48979592])

#**Seleção com array NumPy**

In [62]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
contator[0]

0

In [65]:
item = 6
index = item - 1
contador[index]

5

In [66]:
contador [-1]

9

In [67]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [68]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [69]:
dados[1][2]

1990.0

In [70]:
dados[1, 2]

1990.0

In [71]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
contador [1:4]

array([1, 2, 3])

In [73]:
contador [1:8:2]

array([1, 3, 5, 7])

In [74]:
contador [::2]

array([0, 2, 4, 6, 8])

In [75]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [76]:
dados 

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [81]:
dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [82]:
dados[:, 1:3][0] / (2019 - dados[:, 1:3][1])

array([ 204.        , 1280.10344828])

In [83]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [85]:
contador[contador > 5]

array([6, 7, 8, 9])

In [86]:
dados [1]

array([2003., 1991., 1990., 2019., 2006.])

In [87]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [88]:
dados[:, dados[1]> 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [89]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)

In [95]:
dados[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

#**Atributos e Métodos**

In [99]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.],
                  [2003., 1991., 1990., 2019., 2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [100]:
dados.shape

(2, 5)

In [101]:
dados.ndim

2

In [102]:
dados.size

10

In [103]:
dados.dtype

dtype('float64')

In [104]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [106]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [107]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [108]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [110]:
contador.reshape((5,2), order = 'C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [111]:
contador.reshape((5,2), order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [113]:
km = [44410.0, 5712.0, 37123.0, 0.0, 25757.0]
anos = [2003, 1991, 1990, 2019, 2006]

In [114]:
info_carros = km + anos
info_carros

[44410.0, 5712.0, 37123.0, 0.0, 25757.0, 2003, 1991, 1990, 2019, 2006]

In [115]:
np.array(info_carros).reshape(2,5)

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [116]:
np.array(info_carros).reshape((5,2), order='F')

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [117]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [119]:
dados_new.resize((3,5), refcheck=False)

In [120]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [121]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [122]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

#**Estatísticas**

In [123]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [124]:
anos.shape

(258,)

In [ ]:
dataset = np.column_stack((anos, km, valor))
dataset

In [126]:
dataset.shape

(258, 3)

In [128]:
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [ ]:
np.mean(dataset, axis = 1)

In [133]:
np.mean(dataset[:, 1])

44499.41472868217

In [134]:
np.mean(dataset[:, 2])

98960.51310077519

In [135]:
np.std(dataset[:, 2])

29754.101150388564

In [136]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [139]:
dataset[:, 1].sum()

11480849.0

In [140]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [141]:
np.sum(dataset[:, 2])

25531812.38

In [142]:
idades = np.array([10, 23, 45, 34, 25])

In [143]:
np.sum(idades) / idades.size

27.4

In [144]:
np.mean(idades)

27.4

In [146]:
idades.mean()

27.4